export { createClient } from "./client.js";
export type { Client, ClientOptions } from "./client.js";
export { PrivilegeLevel } from "./v1/common.js";
export type {
  ApiRequest,
  ApiSuccessResponse,
  ApplyAdvancedGameSettingsRequest,
  ApplyAdvancedGameSettingsResponse,
  BooleanString,
  ClaimServerRequest,
  ClaimServerResponse,
  ClaimServerResponseData,
  ErrorResponse,
  GetAdvancedGameSettingsRequest,
  GetAdvancedGameSettingsResponse,
  GetAdvancedGameSettingsResponseData,
  GetServerOptionsRequest,
  GetServerOptionsResponse,
  GetServerOptionsResponseData,
  HealthCheckRequest,
  HealthCheckResponse,
  HealthCheckResponseData,
  InsufficientScopeErrorResponse,
  InvalidTokenErrorResponse,
  MissingParamsErrorResponse,
  PasswordLoginRequest,
  PasswordLoginResponse,
  PasswordLoginResponseData,
  PasswordlessLoginRequest,
  PasswordlessLoginResponse,
  PasswordlessLoginResponseData,
  QueryServerStateRequest,
  QueryServerStateResponse,
  QueryServerStateResponseData,
  VerifyAuthenticationTokenRequest,
  VerifyAuthenticationTokenResponse,
  WrongPasswordErrorResponse,
  RenameServerRequest,
  RenameServerResponse,
  ServerClaimedErrorResponse,
} from "./v1/index.js";
