export { createClient } from "./client.js";
export type { Client, ClientOptions } from "./client.js";
export { PrivilegeLevel } from "./v1/common.js";
export type {
  ApiRequest,
  ApiSuccessResponse,
  ApplyAdvancedGameSettingsRequest,
  ApplyAdvancedGameSettingsResponse,
  BooleanString,
  CannotResetAdminPasswordErrorResponse,
  ClaimServerRequest,
  ClaimServerResponse,
  ClaimServerResponseData,
  ErrorResponse,
  GetAdvancedGameSettingsRequest,
  GetAdvancedGameSettingsResponse,
  GetAdvancedGameSettingsResponseData,
  GetServerOptionsRequest,
  GetServerOptionsResponse,
  GetServerOptionsResponseData,
  HealthCheckRequest,
  HealthCheckResponse,
  HealthCheckResponseData,
  InsufficientScopeErrorResponse,
  InvalidTokenErrorResponse,
  MissingParamsErrorResponse,
  PasswordInUseErrorResponse,
  PasswordLoginRequest,
  PasswordLoginResponse,
  PasswordLoginResponseData,
  PasswordlessLoginRequest,
  PasswordlessLoginResponse,
  PasswordlessLoginResponseData,
  QueryServerStateRequest,
  QueryServerStateResponse,
  QueryServerStateResponseData,
  RenameServerRequest,
  RenameServerResponse,
  ServerClaimedErrorResponse,
  ServerNotClaimedErrorResponse,
  SetAdminPasswordRequest,
  SetAdminPasswordResponse,
  SetAutoLoadSessionNameRequest,
  SetAutoLoadSessionNameResponse,
  SetClientPasswordRequest,
  SetClientPasswordResponse,
  VerifyAuthenticationTokenRequest,
  VerifyAuthenticationTokenResponse,
  WrongPasswordErrorResponse,
} from "./v1/index.js";
